name: Compilar y Ejecutar Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compilar
        run: |
          mkdir -p out
          find src -name "*.java" > sources.txt
          javac -d out @sources.txt

      - name: Ejecutar Main
        run: |
          java -cp out Main